service:
  name: servizs-api

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-plugin-typescript
  - serverless-offline
custom:
  environment: dev

provider:
  name: aws
  runtime: nodejs8.10
  profile: default # AWS CLI profile name
  stage: ${self:custom.environment}
  region: ${file(./config.yml):${self:custom.environment}.REGION}
  iamRoleStatements:
    - Effect: Allow
      Action: 
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${file(./config.yml):${self:custom.environment}.REGION}:*:*"

provider:
  name: aws
  runtime: nodejs8.10

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello



# ------------ database-config -------------

resources:
  Resources:
    UserProfleTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Delete
      Properties: 
        AttributeDefinitions: 
          -
            AttributeName: UerId
            AttributeType: S
            AttributeName: FirstName
            AttributeType: S
            AttributeName: LastName
            AttributeType: S
            AttributeName: EmailAddress
            AttributeType: S
            AttributeName: DateOfBirth
            AttributeType: S

          KeySchema :
            -
              AttributeName: UserId
              KeyType: HASH

            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1

            TableName: "User_Profle_${file(./config.yml):${self:custom.environment}.DB_PREFIX}"

package:
  exclude:
    - node_modules/**/*
